version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - static_volume:/static
      - media_volume:/media
    command: >
      sh -c "python3 manage.py wait_for_db &&
              python3 manage.py migrate &&
              python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=dbuser
      - DB_PASSWORD=django123
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=django123


volumes:
  postgres-data:
  static_volume:
  media_volume:
